/* ===============================
   EXERCISE 04 – QUERYING RECORDS
   =============================== */

-- 1
EXEC sp_help COURSE_INFO;

-- 2
SELECT ZIP_CODE, CITY, STATE AS STATE_CODE FROM ZIPCODE_INFO;

-- 4
SELECT DISTINCT STATE FROM ZIPCODE_INFO;

-- 5
SELECT STUDENT_ID,
       STUDENT_FIRST_NAME + ' ' + STUDENT_LAST_NAME AS NAME
FROM STUDENT_INFO;

-- 6
SELECT ZIP_CODE + ', ' + CITY + ', ' + STATE AS Address
FROM ZIPCODE_INFO;

-- 7
SELECT COURSE_NAME FROM COURSE_INFO;

-- 8
SELECT COURSE_NAME, COST FROM COURSE_INFO;

-- 9
SELECT * FROM COURSE_INFO;

-- 10
SELECT INSTRUCTOR_LAST_NAME, ZIP_CODE FROM INSTRUCTOR_INFO;

-- 11
SELECT DISTINCT ZIP_CODE FROM STUDENT_INFO;

-- 12
SELECT STUDENT_FIRST_NAME, STUDENT_LAST_NAME FROM STUDENT_INFO;

-- 13
SELECT CITY, STATE, ZIP_CODE FROM ZIPCODE_INFO;


/* ===== SELECT WITH WHERE ===== */

-- 1
SELECT STUDENT_ID, SECTION_ID, NUMERIC_GRADE
FROM GRADE_INFO
WHERE GRADE_TYPE_CODE = 'FI';

-- 2
SELECT ZIP_CODE, CITY
FROM ZIPCODE_INFO
WHERE STATE = 'MI';

-- 3
SELECT s.STUDENT_ID,
       s.STUDENT_FIRST_NAME + ' ' + s.STUDENT_LAST_NAME AS NAME
FROM STUDENT_INFO s
JOIN ENROLLMENT_INFO e ON s.STUDENT_ID = e.STUDENT_ID
WHERE MONTH(e.ENROLLMENT_DATE) = 1
  AND YEAR(e.ENROLLMENT_DATE) = 1999
ORDER BY NAME;

-- 4
SELECT SECTION_ID, INSTRUCTOR_ID
FROM SECTION_INFO
WHERE COURSE_NO IN (10, 20)
ORDER BY INSTRUCTOR_ID;

-- 5
SELECT STUDENT_ID, SECTION_ID, NUMERIC_GRADE
FROM GRADE_INFO
ORDER BY SECTION_ID ASC, NUMERIC_GRADE DESC;

-- 6
SELECT COURSE_NO, COURSE_NAME, COST
FROM COURSE_INFO
WHERE COURSE_NAME LIKE '%Intro%';

-- 7
SELECT * FROM COURSE_INFO
WHERE COURSE_NAME LIKE '%a__';

-- 8
SELECT STUDENT_FIRST_NAME, STUDENT_LAST_NAME
FROM STUDENT_INFO
WHERE STUDENT_ID BETWEEN 300 AND 350;

-- 9
SELECT * FROM COURSE_INFO
WHERE COST BETWEEN 4000 AND 7000;

-- 10
SELECT INSTRUCTOR_FIRST_NAME
FROM INSTRUCTOR_INFO
WHERE INSTRUCTOR_LAST_NAME = 'Schumer';

-- 11
SELECT INSTRUCTOR_FIRST_NAME
FROM INSTRUCTOR_INFO
WHERE INSTRUCTOR_LAST_NAME <> 'Schumer';

-- 12
SELECT COURSE_NAME, COST
FROM COURSE_INFO
WHERE COST > 4000;

-- 13
SELECT COURSE_NAME, COST
FROM COURSE_INFO
WHERE COST BETWEEN 3000 AND 7000;

-- 14
SELECT COURSE_NAME, COST
FROM COURSE_INFO
WHERE COST IN (4000, 4500);

-- 15
SELECT STUDENT_FIRST_NAME, STREET_ADDRESS
FROM STUDENT_INFO
WHERE STUDENT_LAST_NAME LIKE 'S%';

-- 16
SELECT STUDENT_FIRST_NAME, STREET_ADDRESS
FROM STUDENT_INFO
WHERE STUDENT_LAST_NAME LIKE '_o%';

-- 17
SELECT INSTRUCTOR_FIRST_NAME
FROM INSTRUCTOR_INFO
WHERE INSTRUCTOR_LAST_NAME NOT LIKE 'S%';

-- 18
SELECT COURSE_NAME, COST
FROM COURSE_INFO
WHERE COST BETWEEN 4000 AND 4500
AND COURSE_NAME LIKE 'I%';

-- 19
SELECT COURSE_NAME, COST, COURSE_PREREQUISITE
FROM COURSE_INFO
WHERE (COST = 2000 AND COURSE_PREREQUISITE = 20)
   OR COURSE_PREREQUISITE = 25;

-- 20
SELECT COURSE_NAME, COST, COURSE_PREREQUISITE
FROM COURSE_INFO
WHERE COST = 2000
   OR COURSE_PREREQUISITE IN (20, 25);

-- 21
SELECT * FROM COURSE_INFO
WHERE COURSE_PREREQUISITE IS NULL;

-- 22
SELECT STUDENT_LAST_NAME
FROM STUDENT_INFO
WHERE ZIP_CODE IN ('10048','11102','11209');

-- 23
SELECT INSTRUCTOR_FIRST_NAME, INSTRUCTOR_LAST_NAME
FROM INSTRUCTOR_INFO
WHERE INSTRUCTOR_LAST_NAME LIKE '%i%'
AND ZIP_CODE = '10025';

-- 24
SELECT COURSE_NAME
FROM COURSE_INFO
WHERE COURSE_PREREQUISITE IS NOT NULL
AND COST < 1100;

-- 25
SELECT DISTINCT COST
FROM COURSE_INFO
WHERE COURSE_PREREQUISITE IS NULL;

-- 26
SELECT COURSE_NO, COURSE_NAME
FROM COURSE_INFO
WHERE COURSE_PREREQUISITE IS NULL
ORDER BY COURSE_NAME;

-- 27
SELECT COURSE_NO, COURSE_NAME
FROM COURSE_INFO
WHERE COURSE_PREREQUISITE IS NULL
ORDER BY COURSE_NAME DESC;

-- 28
SELECT CITY, STATE, ZIP_CODE
FROM ZIPCODE_INFO
WHERE STATE IN ('NY','CT')
ORDER BY ZIP_CODE;

-- 29
SELECT ZIP_CODE, STUDENT_FIRST_NAME, STUDENT_LAST_NAME
FROM STUDENT_INFO
WHERE STUDENT_LAST_NAME = 'Graham'
ORDER BY ZIP_CODE DESC, STUDENT_FIRST_NAME ASC;

-- 30
SELECT CITY + ', ' + STATE AS City_State
FROM ZIPCODE_INFO;

-- 31
SELECT UPPER(LEFT(STUDENT_FIRST_NAME,1)) +
       LOWER(SUBSTRING(STUDENT_FIRST_NAME,2,LEN(STUDENT_FIRST_NAME)))
FROM STUDENT_INFO;

-- 32
SELECT INSTRUCTOR_FIRST_NAME + ', ' + INSTRUCTOR_LAST_NAME AS Instructor_Name
FROM INSTRUCTOR_INFO;

-- 33
SELECT COST,
       COST + 10 AS Add_10,
       COST - 20 AS Sub_20,
       COST * 30 AS Mul_30,
       COST / 5 AS Div_5
FROM COURSE_INFO;

-- 34
SELECT DISTINCT NUMERIC_GRADE,
       CAST(NUMERIC_GRADE / 2 AS INT) AS Half_Grade
FROM GRADE_INFO;


/* ===== FORMAT / CASE / IS NULL ===== */

-- 1
SELECT FORMAT(COST,'N0') AS COST
FROM COURSE_INFO
WHERE COURSE_NO < 25;

-- 2
SELECT '$' + FORMAT(COST,'N2') AS COST
FROM COURSE_INFO;

-- 3
SELECT COURSE_NAME,
       ISNULL(CAST(COURSE_PREREQUISITE AS VARCHAR),'Not Applicable') AS Prerequisite
FROM COURSE_INFO;

-- 4
SELECT CITY,
       CASE
           WHEN STATE = 'NY' THEN 'New York'
           WHEN STATE = 'NJ' THEN 'New Jersey'
           ELSE 'Others'
       END AS STATE_NAME
FROM ZIPCODE_INFO;
