-- 1. ZIPCODE_INFO
CREATE TABLE ZIPCODE_INFO
(
    ZIP_CODE VARCHAR(5),
    CITY VARCHAR(10)
);
GO

-- 2. INSTRUCTOR_INFO
CREATE TABLE INSTRUCTOR_INFO
(
    INSTRUCTOR_ID NUMERIC(8,0),
    INSTRUCTOR_FIRST_NAME VARCHAR(15),
    INSTRUCTOR_LAST_NAME VARCHAR(15)
);
GO

-- 3. COURSE_INFO
CREATE TABLE COURSE_INFO
(
    COURSE_NO NUMERIC(8,0),
    COST NUMERIC(5,2)
);
GO

-- 4. STUDENT_INFO
CREATE TABLE STUDENT_INFO
(
    STUDENT_ID NUMERIC(8,0),
    STUDENT_FIRST_NAME VARCHAR(15),
    STUDENT_LAST_NAME VARCHAR(15)
);
GO

-- 5. SECTION_INFO
CREATE TABLE SECTION_INFO
(
    SECTION_ID NUMERIC(8,0),
    COURSE_NO NUMERIC(8,0),
    SECTION_NO NUMERIC(5,0),
    INSTRUCTOR_ID NUMERIC(8,0)
);
GO

-- 6. ENROLLMENT_INFO
CREATE TABLE ENROLLMENT_INFO
(
    STUDENT_ID NUMERIC(8,0),
    SECTION_ID NUMERIC(8,0)
);
GO

-- 7. GRADE_INFO
CREATE TABLE GRADE_INFO
(
    STUDENT_ID NUMERIC(8,0),
    SECTION_ID NUMERIC(8,0),
    GRADE_TYPE_CODE CHAR(2),
    GRADE_CODE_OCCURANCE NUMERIC(5,0)
);
GO
